import { cached } from '../cache.js';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

/**
 * Video to text.
 *
 * YouTube's public Data API will not hand over caption bodies without the
 * owner's OAuth token, so this reads the player response on the watch page and
 * fetches the caption track the player itself uses. Works for any video with
 * captions (including auto-generated ones).
 */
export async function fetchTranscript(videoId, { language = 'en' } = {}) {
  const id = String(videoId || '').trim();
  if (!/^[\w-]{11}$/.test(id)) {
    const error = new Error('That does not look like a YouTube video id or URL.');
    error.status = 400;
    throw error;
  }
  return cached(`transcript:${id}:${language}`, async () => {
    const tracks = await captionTracks(id);
    if (!tracks.length) {
      const error = new Error('No caption track is available for this video. Try a different video, or narrate from the description instead.');
      error.status = 404;
      throw error;
    }
    const track = pickTrack(tracks, language);
    const segments = await fetchTrack(track.baseUrl);
    const text = segments.map((segment) => segment.text).join(' ').replace(/\s+/g, ' ').trim();
    const words = text.split(/\s+/).filter(Boolean).length;
    return {
      videoId: id,
      language: track.languageCode,
      trackName: track.name,
      autoGenerated: track.kind === 'asr',
      availableLanguages: tracks.map((t) => ({ code: t.languageCode, name: t.name, auto: t.kind === 'asr' })),
      segments,
      text,
      words,
      characters: text.length,
      readingTimeSeconds: Math.round((words / 150) * 60),
      paragraphs: toParagraphs(segments),
    };
  }, 60 * 60 * 1000);
}

async function captionTracks(videoId) {
  const response = await fetch(`https://www.youtube.com/watch?v=${videoId}&hl=en`, {
    headers: { 'user-agent': UA, 'accept-language': 'en-US,en;q=0.9' },
  });
  if (!response.ok) {
    const error = new Error(`Could not load the watch page (HTTP ${response.status}).`);
    error.status = 502;
    throw error;
  }
  const html = await response.text();
  const player = extractPlayerResponse(html);
  const tracks = player?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
  return tracks.map((track) => ({
    baseUrl: track.baseUrl,
    languageCode: track.languageCode,
    kind: track.kind,
    name: track.name?.simpleText || track.name?.runs?.[0]?.text || track.languageCode,
  }));
}

/** Pull ytInitialPlayerResponse out of the watch page HTML. */
export function extractPlayerResponse(html) {
  const marker = 'ytInitialPlayerResponse';
  const start = html.indexOf(marker);
  if (start === -1) return null;
  const brace = html.indexOf('{', start);
  if (brace === -1) return null;
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = brace; i < html.length; i += 1) {
    const char = html[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (char === '\\') escaped = true;
      else if (char === '"') inString = false;
      continue;
    }
    if (char === '"') inString = true;
    else if (char === '{') depth += 1;
    else if (char === '}') {
      depth -= 1;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(brace, i + 1));
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

function pickTrack(tracks, language) {
  const lang = String(language || 'en').toLowerCase();
  return tracks.find((t) => t.languageCode?.toLowerCase() === lang && t.kind !== 'asr')
    || tracks.find((t) => t.languageCode?.toLowerCase() === lang)
    || tracks.find((t) => t.languageCode?.toLowerCase().startsWith(lang.slice(0, 2)))
    || tracks[0];
}

async function fetchTrack(baseUrl) {
  const url = new URL(baseUrl);
  url.searchParams.set('fmt', 'json3');
  const response = await fetch(url, { headers: { 'user-agent': UA } });
  const body = await response.text();
  if (response.ok && body.trim().startsWith('{')) {
    const data = JSON.parse(body);
    return (data.events || [])
      .filter((event) => Array.isArray(event.segs))
      .map((event) => ({
        start: Math.round((event.tStartMs || 0) / 100) / 10,
        duration: Math.round((event.dDurationMs || 0) / 100) / 10,
        text: event.segs.map((seg) => seg.utf8 || '').join('').replace(/\n/g, ' ').trim(),
      }))
      .filter((segment) => segment.text);
  }
  // Fall back to the older XML format.
  return parseTimedTextXml(body);
}

export function parseTimedTextXml(xml) {
  const out = [];
  const pattern = /<text start="([\d.]+)"(?: dur="([\d.]+)")?[^>]*>([\s\S]*?)<\/text>/g;
  let match;
  while ((match = pattern.exec(xml)) !== null) {
    const text = decodeEntities(match[3]).replace(/\s+/g, ' ').trim();
    if (!text) continue;
    out.push({ start: Number(match[1]), duration: Number(match[2] || 0), text });
  }
  return out;
}

function decodeEntities(text) {
  return String(text)
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)));
}

/** Group caption segments into readable paragraphs with timestamps. */
export function toParagraphs(segments, { secondsPerParagraph = 45 } = {}) {
  const paragraphs = [];
  let current = null;
  for (const segment of segments) {
    if (!current || segment.start - current.start >= secondsPerParagraph) {
      if (current) paragraphs.push(current);
      current = { start: segment.start, text: segment.text };
    } else {
      current.text += ` ${segment.text}`;
    }
  }
  if (current) paragraphs.push(current);
  return paragraphs.map((p) => ({
    start: p.start,
    timestamp: stamp(p.start),
    text: p.text.replace(/\s+/g, ' ').trim(),
  }));
}

export function stamp(seconds) {
  const total = Math.max(0, Math.floor(seconds));
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m}:${String(s).padStart(2, '0')}`;
}
